// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock.Data;

namespace Stock.WebAPI.Migrations
{
    [DbContext(typeof(StockContext))]
    [Migration("20200313120419_alterColumn")]
    partial class alterColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Stock.Model.Price", b =>
                {
                    b.Property<byte>("Unit")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(15) CHARACTER SET utf8mb4")
                        .HasMaxLength(15);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Avg")
                        .HasColumnType("double");

                    b.Property<double>("Close")
                        .HasColumnType("double");

                    b.Property<double>("High")
                        .HasColumnType("double");

                    b.Property<double>("Highlimit")
                        .HasColumnType("double");

                    b.Property<double>("Low")
                        .HasColumnType("double");

                    b.Property<double>("Lowlimit")
                        .HasColumnType("double");

                    b.Property<double>("Money")
                        .HasColumnType("double");

                    b.Property<double>("Open")
                        .HasColumnType("double");

                    b.Property<bool>("Paused")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Preclose")
                        .HasColumnType("double");

                    b.Property<double>("Volume")
                        .HasColumnType("double");

                    b.HasKey("Unit", "Code", "Date");

                    b.ToTable("PriceSet");
                });

            modelBuilder.Entity("Stock.Model.Securities", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(15) CHARACTER SET utf8mb4")
                        .HasMaxLength(15);

                    b.Property<string>("Displayname")
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("SecuritiesSet");
                });
#pragma warning restore 612, 618
        }
    }
}
