@host =http://localhost:53791
@authToken  = ""
### test basic api
GET {{host}}/weatherforecast HTTP/1.1


### login request
# @name login
POST  {{host}}/api/Auth/login HTTP/1.1
Content-Type: application/json

{
	"email":"hammergo@163.com",
	"password":"dragon"
}

 
### 获取股票日线数据
@authToken = {{login.response.body.token}}

GET {{host}}/api/Values/0600000
Authorization: Bearer {{authToken}}

### MA 2u次突破测试
POST {{host}}/api/search/UpMATwice HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "stockIdList": [
        "0601138"
    ],
    "AvgDays": 60,
    "RecentDaysNum": 7,
     "MaxDaysNumDownAvgBeforeTwice": 2,
      "MaxDaysNumUpAvgAfterFirst": 8,
    "MinDaysNumDownAvgBeforeFirst": 20,
    "MaxDaysNumUpAvgBeforeFirst": 0,
   
   
    "searchFromAllStocks": false,
    "baseDate": "9999-12-31T23:59:59.9999999"
}


###  统计涨幅的测试
POST {{host}}/api/search/STAArise HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "stockIdList": [
        "0601138"
    ],
    
  "dateList" :[
      "2020-06-16" 
  ],
   
    "searchFromAllStocks": false,
    "baseDate": "9999-12-31"
}



### 中价突破测试
POST {{host}}/api/search/MiddleBreak HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "stockIdList": [
        "1002425"
    ],
     "huiTiaoFuDuLow": 9,
    "huiTiaoFuDuHigh": 25.0,
    "nearDaysNum": 1,
    "circleDaysNum": 60,
   
    "searchFromAllStocks": false,
    "baseDate": "2020-05-28"
}

### 平台突破测试，严格模式
POST {{host}}/api/search/ColseBreak HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "stockIdList": [
        "1002425"
    ],
    "strictMode":true,
     "huiTiaoFuDuLow": 9.5,
    "huiTiaoFuDuHigh": 25.0,
    "nearDaysNum": 1,
    "circleDaysNum": 60,
   
    "searchFromAllStocks": false,
    "baseDate": "2020-05-28"
}


### 平台突破测试，宽松模式
POST {{host}}/api/search/ColseBreak HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "stockIdList": [
        "1002425"
    ],
    "strictMode":false,
     "huiTiaoFuDuLow": 9.5,
    "huiTiaoFuDuHigh": 25.0,
    "nearDaysNum": 1,
    "circleDaysNum": 60,
   
    "searchFromAllStocks": false,
    "baseDate": "2020-05-28"
}


### 平台突破测试
POST {{host}}/api/search/ColseBreak HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "stockIdList": [
        "0603060"
    ],
     "huiTiaoFuDuLow": 9.5,
    "huiTiaoFuDuHigh": 25.0,
    "nearDaysNum": 1,
    "circleDaysNum": 60,
   
    "searchFromAllStocks": false,
    "baseDate": "2020-06-01"
}
